Feature test runner procedure
BREAD5940/BREAD-Robot-Core pull request #75
Opened 2017-02-28 01:20 UTC by bertturtle

2017-03-01 03:37 UTC, themacman commented
>tfw david reviews loeffler's pull request and not yours

2017-03-02 01:26 UTC, david-boles requested changes

2017-03-02 01:26 UTC, david476 commented on src/org/team5940/robot_core/modules/testing/runners/MultipleTestRunnerProcedureModule.java
> + * A {@link AbstractProcedureModule} that runs tests on {@link TestableModule}.
.. runs tests on on +a ...

2017-03-02 01:26 UTC, david476 commented on src/org/team5940/robot_core/modules/testing/runners/MultipleTestRunnerProcedureModule.java
> +		testThread = new TestThread(this.communicationModule, this.testableModules);
Interrupt the old thread if not null.

2017-03-02 01:26 UTC, david476 commented on src/org/team5940/robot_core/modules/testing/runners/MultipleTestRunnerProcedureModule.java
> +		testThread.interrupt();
Reset to null

2017-03-02 01:26 UTC, david476 commented on src/org/team5940/robot_core/modules/testing/runners/MultipleTestRunnerProcedureModule.java
> +		testThread = new TestThread(this.communicationModule, this.testableModules);
NVM

2017-03-02 01:26 UTC, david476 commented on src/org/team5940/robot_core/modules/testing/runners/MultipleTestRunnerProcedureModule.java
> +	ModuleHashtable<TestableModule> testableModules;
Make all variables private and except for thread final

2017-03-02 01:26 UTC, david476 commented on src/org/team5940/robot_core/modules/testing/runners/MultipleTestRunnerProcedureModule.java
> +		TestCommunicationModule communicationModule;
Same private and final variable dealio, document

2017-03-02 01:26 UTC, david476 commented on src/org/team5940/robot_core/modules/testing/runners/MultipleTestRunnerProcedureModule.java
> +		private boolean isAssignableToString(String className, Class<?> module) {
Document

2017-03-02 01:26 UTC, david476 commented on src/org/team5940/robot_core/modules/testing/runners/MultipleTestRunnerProcedureModule.java
> +				while (!this.completed) {
Switch to just using interruption

2017-03-02 01:26 UTC, david476 commented on src/org/team5940/robot_core/modules/testing/runners/MultipleTestRunnerProcedureModule.java
> +						} while (testModule == null);
Check for thread interruption.

2017-03-02 01:26 UTC, david476 commented on src/org/team5940/robot_core/modules/testing/runners/MultipleTestRunnerProcedureModule.java
> +import com.sun.org.apache.bcel.internal.generic.Type;
Remove import

2017-03-02 01:36 UTC, david-boles approved these changes

2017-03-02 01:52 UTC, merged